# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bdf581dbff5063567695a376825e9666"
name = "shopiapp"
handle = "shopiapp-27"
application_url = "https://grew-spoke-fails-scenario.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6f32df40.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://grew-spoke-fails-scenario.trycloudflare.com/auth/callback",
  "https://grew-spoke-fails-scenario.trycloudflare.com/auth/shopify/callback",
  "https://grew-spoke-fails-scenario.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
